var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/diagnosis/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o7tx_s._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_11f1-6_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l20r2a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_diagnosis_page_actions_0lljc_t.js")
R.m(70843)
module.exports=R.m(70843).exports
